"""initial schema

Revision ID: 08a38ba662ba
Revises: 
Create Date: 2026-06-19 13:38:06.576551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a38ba662ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedural_memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('technique', sa.Text(), nullable=False),
    sa.Column('effectiveness', sa.Float(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procedural_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procedural_memories_context'), ['context'], unique=False)

    op.create_table('semantic_memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('semantic_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semantic_memories_key'), ['key'], unique=True)

    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('modality', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('local_model', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dreams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('feelings', sa.Text(), nullable=False),
    sa.Column('symbols', sa.Text(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('dream_date', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dreams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dreams_session_id'), ['session_id'], unique=False)

    op.create_table('episodic_memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_id', sa.String(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('properties', sa.Text(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('first_seen', sa.String(), nullable=False),
    sa.Column('last_seen', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_nodes_label'), ['label'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('note_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_session_id'), ['session_id'], unique=False)

    op.create_table('safety_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safety_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_events_session_id'), ['session_id'], unique=False)

    op.create_table('voice_recordings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_recordings_session_id'), ['session_id'], unique=False)

    op.create_table('graph_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graph_edges')
    with op.batch_alter_table('voice_recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_recordings_session_id'))

    op.drop_table('voice_recordings')
    with op.batch_alter_table('safety_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_events_session_id'))

    op.drop_table('safety_events')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_session_id'))

    op.drop_table('notes')
    op.drop_table('messages')
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_nodes_label'))

    op.drop_table('graph_nodes')
    op.drop_table('episodic_memories')
    with op.batch_alter_table('dreams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dreams_session_id'))

    op.drop_table('dreams')
    op.drop_table('sessions')
    with op.batch_alter_table('semantic_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semantic_memories_key'))

    op.drop_table('semantic_memories')
    with op.batch_alter_table('procedural_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procedural_memories_context'))

    op.drop_table('procedural_memories')
    # ### end Alembic commands ###
